# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QNTRIPClient
                                 A QGIS plugin
 NTRIP client for qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-28
        copyright            : (C) 2025 by Manuel Hart (Geokoord.com)
        email                : mh@geokoord.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QNTRIPClient class from file QNTRIPClient.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .q_ntrip_client import QNTRIPClient
    return QNTRIPClient(iface)
